//import * as testExample from '/test/test-example.js';
import * as testDominoTile from './test-domino-tile.js';
import * as testDomino from './test-domino.js';
import * as testBoardMinMaxAxis from './test-board-min-max-axis.js';
import * as testGameBoardManager from './test-game-board-manager.js';
import * as testGameConfiguration from './test-game-configuration.js';
import * as testWebGameManager from './test-web-game-manager.js';
import * as testBoardScoring from './test-board-scoring.js';
import * as testGameAdvisor from './test-game-advisor.js';
